version: '3'

networks:
  default:
    external:
      name: nginx-proxy

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: pixonic.api
      HSTS: "max-age=131072"


