version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 81:81
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  dbms:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1